events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location /api/pedidos {
            proxy_pass http://pedidos-service:3000/pedidos;
        }

        location /api/pagamentos {
            proxy_pass http://pagamentos-service:5000/pagamentos;
        }

        location /api/estoque {
            proxy_pass http://estoque-service:8080/estoque;
        }

        location /health {
            return 200 '{"status": "API Gateway is healthy"}';
            add_header Content-Type application/json;
        }
    }
}
